include:
  - project: 'DevOps/templates'
    ref: 'v2.0.3'
    file:
      - '.compile/js.yml'
      - '.build/npm.yml'
      - '.build/docker.yml'
      - '.deploy/cloudfront.yml'

image: 'node:20'

variables:
  s3_bucket_production: "checkout-sdk.sezzle.com"
  cf_dist_production: "EQ8554SMUE81E"
  JIRA_PROJECT_NAME: "MINT"