################
#   GLOBALS    #
################
include:
  - project: 'DevOps/templates'
    file: '/js/defaults.yml'
  - project: 'DevOps/templates'
    file: '/js/jest_tests.yml'
  - project: 'DevOps/templates'
    file: '/js/build.yml'
  - project: 'DevOps/templates'
    file: '/cloudfront/deploy.yml'

image: 'node:12'

variables:
  JIRA_PROJECT_NAME: "MINT"
  PRODUCTION_INCLUDES_SANDBOX: "true"

#############
#   DEPLOY  #
#############

deploy_production:
  stage: deploy
  variables:
    S3_BUCKET: "checkout-sdk.sezzle.com"
    CF_DIST: "EQ8554SMUE81E"

deploy_sandbox:
  stage: deploy
  variables:
    S3_BUCKET: "sandbox.checkout-sdk.sezzle.com"
    CF_DIST: "E14UFWT5883J1I"
